CREATE TABLE regions(
REGION_ID INT NOT NULL,
REGION_NAME CHAR(50) NOT NULL,
CONSTRAINT PRIMARY KEY (REGION_ID)
);

CREATE TABLE countries(
COUNTRY_ID	CHAR(2)	NOT	NULL,
COUNTRY_NAME VARCHAR(40)	NOT	NULL,
REGION_ID INT NOT NULL,
CONSTRAINT PRIMARY KEY (COUNTRY_ID, REGION_ID),
FOREIGN KEY (REGION_ID)
REFERENCES regions(REGION_ID)
);

CREATE TABLE locations(
LOCATION_ID	INT NOT NULL,
STREET_ADRDRESS VARCHAR(25) NOT NULL,
POSTAL_CODE	VARCHAR(12) NOT NULL,
CITY VARCHAR(30) NOT NULL,
STATE_PROVINCE VARCHAR(12) NOT NULL,
COUNTRY_ID CHAR(2) NOT NULL,
CONSTRAINT PRIMARY KEY (LOCATION_ID, COUNTRY_ID),
FOREIGN KEY(COUNTRY_ID)
REFERENCES countries(COUNTRY_ID)
);

CREATE TABLE departments(
DEPARTMENT_ID INT NOT NULL,
DEPARTMENT_NAME	VARCHAR(20) NOT NULL,
MANAGER_ID INT NOT NULL,
LOCATION_ID INT NOT NULL,
CONSTRAINT PRIMARY KEY (DEPARTMENT_ID,LOCATION_ID),
FOREIGN KEY(LOCATION_ID)
REFERENCES locations(LOCATION_ID)
);

CREATE TABLE EMPLOYEES(
EMPLOYEE_ID INT NOT NULL,
FIRST_NAME VARCHAR(20) NOT NULL,
LAST_NAME VARCHAR(25) NOT NULL,
EMAIL VARCHAR(30) NOT NULL,
PHONE_NUMBER VARCHAR(20) NOT NULL,
HIRE_DATE DATE NOT NULL,
JOB_ID VARCHAR(10) NOT NULL,
SALARY INT NOT NULL,
COMMISSION_PCT INT NOT NULL,
MANAGER_ID INT NOT NULL,
DEPARTMENT_ID INT NOT NULL,
CONSTRAINT PRIMARY KEY (EMPLOYEE_ID,DEPARTMENT_ID,JOB_ID),
FOREIGN KEY (DEPARTMENT_ID)
REFERENCES departments(DEPARTMENT_ID),
FOREIGN KEY (JOB_ID)
REFERENCES job_history(JOB_ID)
);

CREATE TABLE jobs(
JOB_ID VARCHAR(20) NOT NULL,
JOB_TITLE VARCHAR(35) NOT NULL,
MIN_SALARY INT NOT NULL,
MAX_SALARY INT NOT NULL,
CONSTRAINT PRIMARY KEY (JOB_ID)
);

CREATE TABLE job_history(
EMPLOYEE_ID INT NOT NULL,
START_DATE DATE NOT NULL,
END_DATE DATE NOT NULL,
JOB_ID VARCHAR(10) NOT NULL,
DEPARTMENT_ID INT NOT NULL,
CONSTRAINT PRIMARY KEY (EMPLOYEE_ID, START_DATE,DEPARTMENT_ID,JOB_ID),
FOREIGN KEY (DEPARTMENT_ID)
REFERENCES departments(DEPARTMENT_ID),
FOREIGN KEY (JOB_ID)
REFERENCES jobs(JOB_ID)
);

CREATE TABLE job_grades(
GRADE_LEVEL VARCHAR(2) NOT NULL,
LOWEST_SAL INT NOT NULL,
HIGHEST_SAL INT NOT NULL,
CONSTRAINT PRIMARY KEY (GRADE_LEVEL)
);



